# Generated by parallelRemake::write_makefile() on 2016-06-08 12:17:57 

.PHONY: all datasets paschold_DE_1000 poisson_DE_1000 clean

all: datasets 

datasets: paschold_DE_1000 poisson_DE_1000 

paschold_DE_1000:  
	Rscript -e 'remake::make("paschold_DE_1000", remake_file = "remake.yml")'

poisson_DE_1000:  
	Rscript -e 'remake::make("poisson_DE_1000", remake_file = "remake.yml")'

clean:
	Rscript -e 'remake::make("clean", remake_file = "remake.yml")'
	rm -rf .remake
